### PR TITLE
change factories paramin swarmprotocol to readonly

### LINKED ISSUE #23: Enable ReadOnly<NonZeroTuple> for RegisteredEventFactories
### Expected: 

`SwarmProtocol.make` should accept Readonly<NonZeroTuple>. See the snippet below

### Actual:

As per latest master https://github.com/Actyx/machines/commit/0efda8e604c6797e668987f51ede5910b1dc01c7 `SwarmProtocol.make` doesn't accept `Readonly<NonZeroTuple>` for the event factories parameters.

### Snippet

```
namespace Events {
  const Opened = MachineEvent.design('opened').withoutPayload()
  const Closed = MachineEvent.design('closed').withoutPayload()
  const Opening = MachineEvent.design('opening').withPayload<{ fractionOpen: number }>()
  const Closing = MachineEvent.design('closing').withPayload<{ fractionOpen: number }>()

  // readonly tuple
  export const all = [Opened, Closed, Opening, Closing] as const;
}

const HangarBay = SwarmProtocol.make('HangarBay', ['hangar-bay'], Events.all)
```

### PR DESCRIPTION
**Pull request by Kelerchian**
resolves #23

### CODE REVIEW

**Comment by rkuhn** [comment]
Yes, this is a good first step, but it doesn’t resolve #23 (or we need to open a new issue with the rest of it). I think all arrays we take in our API are in fact readonly, and the event payloads returned from command handlers can probably also be readonly.

**Comment by Kelerchian** [comment]
> Yes, this is a good first step, but it doesn’t resolve #23 (or we need to open a new issue with the rest of it). I think all arrays we take in our API are in fact readonly, and the event payloads returned from command handlers can probably also be readonly.

Could you elaborate more? Apart from the "defensive copy" part that I missed, I don't understand which checkbox isn't ticked

**Comment by rkuhn** [comment]
Ah, I see you did more than what the description says. But it isn’t obvious from the diff which parts of the API were changed. It would be good to demonstrate all new `readonly` capabilities by changing the types in our examples and tests and seeing that those still compile. For example, from the diff I can’t judge whether it is now okay to return some `readonly` types from a command handler.

**Review by jmg-duarte — APPROVED** [review]

**Comment by Kelerchian** [comment]
> Ah, I see you did more than what the description says. But it isn’t obvious from the diff which parts of the API were changed. It would be good to demonstrate all new `readonly` capabilities by changing the types in our examples and tests and seeing that those still compile. For example, from the diff I can’t judge whether it is now okay to return some `readonly` types from a command handler.

Ah. Right.

**Comment by Kelerchian** [comment]
Example is available in dev-example/src/machines/protocol.ts

**Pull request merged**
